version: '3.1'

volumes:
    grafana_config_data: {}
    grafana_data: {}
    prometheus_config_data: {}
    elasticsearch_config_data: {}
    logstash_config_data: {}
    influxdb_config_data: {}
#    grafana_dashboards: {}

networks:
  plei:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    volumes:
      - elasticsearch_config_data:/usr/share/elasticsearch/config/
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - plei
    depends_on:
      - logstash

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    volumes:
      - logstash_config_data:/usr/share/logstash/config/
    ports:
      - "5140:5140/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - plei

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb_config_data:/etc/influxdb/
    ports:
      - "8086:8086"
#    environment:
#      - INFLUXDB_DB=cadvisor
    networks:
      - plei
    depends_on:
      - logstash

  grafana:
    image: grafana/grafana:5.3.2
    volumes:
      - grafana_config_data:/etc/grafana/
      - grafana_data:/var/lib/grafana/
#      - grafana_dashboards:/var/lib/grafana/dashboards
#    environment:
#      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
#      - GF_LOG_LEVEL=debug
#      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
#      - GF_PATHS_DATA=/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - plei
    depends_on:
      - logstash

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_config_data:/etc/prometheus/
    ports:
      - "9090:9090"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5140"
        syslog-format: "rfc3164"
        tag: "{{.Name}}/{{.ID}}"
    networks:
      - plei
    depends_on:
      - logstash

  source:
    image: containerize/git
    environment:
      - REPO_LOCAL=/data/git/repos/plei
      - REPO_BRANCH=PWD
      - REPO_REMOTE=https://github.com/crab86/grafana-plei.git
    tty: true
    volumes:
      - prometheus_config_data:/data/git/repos/plei/prometheus
      - grafana_config_data:/data/git/repos/plei/grafana/config
      - elasticsearch_config_data:/data/git/repos/plei/elasticsearch/config
      - logstash_config_data:/data/git/repos/plei/logstash
      - influxdb_config_data:/data/git/repos/plei/influxdb
#      - grafana_dashboards:/data/git/repos/plei/grafana/var/lib/grafana/dashboards
