{
 "title": "Logstash Monitoring based on X-Pack stats - repeat by node",
 "description": "Logstash monitoring based on internal X-Pack statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "query": "{\"find\": \"terms\", \"field\": \"logstash_stats.logstash.name\", \"limit\": 1000}"
   }
  ]
 },
 "panels": [
  { "title": "General Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "12",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "logstash_stats.logstash.version",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "logstash_stats.process.cpu.percent",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "logstash_stats.os.cpu.load_average.1m",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "logstash_stats.jvm.mem.heap_used_percent",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "logstash_stats.events.in",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "logstash_stats.reloads.successes",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "logstash_stats.reloads.failures",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Specific Node Overview - $node_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "node_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Node Information - $node_name",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "logstash_stats.logstash.name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "logstash_stats.logstash.http_address",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "logstash_stats.logstash.version",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "logstash_stats.events.in",
         "id": "1",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "avg"
        },
        {
         "field": "logstash_stats.events.out",
         "id": "6",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "logstash_stats.reloads.successes",
         "id": "7",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "logstash_stats.reloads.failures",
         "id": "8",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "logstash_stats.logstash.pipeline.batch_size",
         "id": "9",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "logstash_stats.logstash.pipeline.workers",
         "id": "12",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "logstash_stats.logstash.status",
         "id": "13",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - Events In /s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Events In",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.events.in",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - Events Filtered /s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Events Filtered",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.events.filtered",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - Events Out /s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Events Out",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.events.out",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - Event Duration in ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Events Duration",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.events.duration_in_millis",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - Process CPU %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Process CPU % - {{term logstash_stats.logstash.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "logstash_stats.logstash.name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.process.cpu.percent",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - JVM Heap Usage in Bytes -",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Heap Max",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.jvm.mem.heap_max_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      },
      {
       "alias": "Head Used",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.jvm.mem.heap_used_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "load_15 - {{term logstash_stats.logstash.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "logstash_stats.logstash.name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.os.cpu.load_average.15m",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      },
      {
       "alias": "load_5 - {{term logstash_stats.logstash.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "logstash_stats.logstash.name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.os.cpu.load_average.5m",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      },
      {
       "alias": "load_1 - {{term logstash_stats.logstash.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "logstash_stats.logstash.name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.os.cpu.load_average.1m",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Specific Node Advanced Stats - $node_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "node_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Logstash - File Descriptors  - $node_name",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Max File Descriptors",
       "bucketAggs": [
        {
         "fake": true,
         "field": "logstash_stats.logstash.name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.process.max_file_descriptors",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      },
      {
       "alias": "Open File Descriptors",
       "bucketAggs": [
        {
         "fake": true,
         "field": "logstash_stats.logstash.name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.process.open_file_descriptors",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Logstash - JVM Garbage Collection Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "GC Young",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.jvm.gc.collectors.young.collection_count",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      },
      {
       "alias": "GC Old",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.jvm.gc.collectors.old.collection_count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Logstash - JVM Garbage Collection Time in ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "GC Young Time",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.jvm.gc.collectors.young.collection_time_in_millis",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      },
      {
       "alias": "GC Old Time",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.jvm.gc.collectors.old.collection_time_in_millis",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - Queue Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Queue Size in Bytes",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.pipelines.queue.queue_size_in_bytes",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      },
      {
       "alias": "Max Queue Size in Bytes",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.pipelines.queue.max_queue_size_in_bytes",
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "logstash_stats.logstash.name:$node_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - Queue Events",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Queue Events",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.queue.events_count",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - CGroup CPU Performance in ns",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "CGroup Usage",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.os.cgroup.cpuacct.usage_nanos",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "CGroup Throttling",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.os.cgroup.cpu.stat.time_throttled_nanos",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$node_name - CGroup FCS Stats",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "CGroup Elapsed Periods",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.os.cgroup.cpu.stat.number_of_elapsed_periods",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "CGroup Throttled Count",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logstash_stats.os.cgroup.cpu.stat.number_of_times_throttled",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}