{
 "title": "Logstash Monitoring based on X-Pack stats - grouped by node",
 "description": "Dashboard to view Logstashs internal statistics (based on X-Pack).",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "query": "{\"find\": \"terms\", \"field\": \"logstash_stats.logstash.name\", \"limit\": 1000}"
   }
  ]
 },
 "panels": [
  { "title": "General Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "12",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "logstash_stats.logstash.version",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "logstash_stats.process.cpu.percent",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "logstash_stats.os.cpu.load_average.1m",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "logstash_stats.jvm.mem.heap_used_percent",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "logstash_stats.events.in",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "logstash_stats.reloads.successes",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "logstash_stats.reloads.failures",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Node Overview - $node_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Node Information - $node_name",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "logstash_stats.logstash.http_address",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "logstash_stats.logstash.version",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "logstash_stats.events.in",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "logstash_stats.events.out",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "logstash_stats.reloads.successes",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "logstash_stats.reloads.failures",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "logstash_stats.logstash.pipeline.batch_size",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "logstash_stats.logstash.pipeline.workers",
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "logstash_stats.logstash.status",
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "logstash_stats.jvm.uptime_in_millis",
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - Events In /s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Events In - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.events.in",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - Events Filtered /s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Events Filtered - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.events.filtered",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - Events Out /s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Events Out - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.events.out",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - Event Duration in ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Events Duration - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.events.duration_in_millis",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - Process CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Process CPU % - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.process.cpu.percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "load_15 - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.os.cpu.load_average.15m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    },
    {
     "alias": "load_5 - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.os.cpu.load_average.5m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    },
    {
     "alias": "load_1 - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.os.cpu.load_average.1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - JVM Heap Usage in Bytes -",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Heap Max - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.jvm.mem.heap_max_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Head Used - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.jvm.mem.heap_used_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - JVM Heap Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Heap Usage in % - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.jvm.mem.heap_used_percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Node Advanced Stats - $node_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Logstash - File Descriptors  - $node_name",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Max File Descriptors - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.process.max_file_descriptors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Open File Descriptors - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.process.open_file_descriptors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Logstash - JVM Garbage Collection Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "GC Young - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.jvm.gc.collectors.young.collection_count",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    },
    {
     "alias": "GC Old - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.jvm.gc.collectors.old.collection_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Logstash - JVM Garbage Collection Time in ms",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "GC Young Time - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.jvm.gc.collectors.young.collection_time_in_millis",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    },
    {
     "alias": "GC Old Time - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.jvm.gc.collectors.old.collection_time_in_millis",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - Queue Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Queue Size in Bytes - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.pipelines.queue.queue_size_in_bytes",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Max Queue Size in Bytes - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.pipelines.queue.max_queue_size_in_bytes",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logstash_stats.logstash.name:$node_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - Queue Events",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Queue Events - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.queue.events_count",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - CGroup CPU Performance in ns",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "CGroup Usage - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.os.cgroup.cpuacct.usage_nanos",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "CGroup Throttling - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.os.cgroup.cpu.stat.time_throttled_nanos",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$node_name - CGroup FCS Stats",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CGroup Elapsed Periods - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.os.cgroup.cpu.stat.number_of_elapsed_periods",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "CGroup Throttled Count - {{term logstash_stats.logstash.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logstash_stats.logstash.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "logstash_stats.os.cgroup.cpu.stat.number_of_times_throttled",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}