apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: InfluxDB_cadvisor
    type: influxdb
    access: proxy
    database: cadvisor
    url: http://influxdb:8086

  - name: InfluxDB_internal
    type: influxdb
    access: proxy
    database: _internal
    url: http://influxdb:8086

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: "[logstash-]YYYY.MM.DD"
    url: http://elasticsearch:9200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 56

  - name: Elasticsearch-monitoring
    type: elasticsearch
    access: proxy
    database: "[.monitoring-es-6-]YYYY.MM.DD"
    url: http://elasticsearch:9200
    jsonData:
      interval: Daily
      timeField: "timestamp"
      esVersion: 56
      timeInterval: "10s"

  - name: Elasticsearch-monitoring-logstash
    type: elasticsearch
    access: proxy
    database: "[.monitoring-logstash-6-]YYYY.MM.DD"
    url: http://elasticsearch:9200
    jsonData:
      interval: Daily
      timeField: "timestamp"
      esVersion: 56
      timeInterval: "10s"
